version: '2'
services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
      args:
        UID: $UID
        GUID: $GUID
    links:
      - php
    ports:
      - $PORT:80
    volumes_from:
      - php
      - frontend
    volumes:
      - "./shared/logs/nginx:/var/log/nginx"
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        UID: $UID
        GUID: $GUID
    links:
      - db
    expose:
      - "9000"
    volumes:
      - "./shared/site:/var/www/site"
  db:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    expose:
      - "5432"
    ports:
      - 7139:5432
    volumes:
      - "./shared/postgresql/data:/var/lib/postgresql/data/pgdata"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: sycast
      POSTGRES_USER: sycast
      POSTGRES_PASSWORD: sycast

  db_test:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    expose:
      - "5432"
    ports:
      - 7139:5432
    volumes:
      - "./shared/postgresql/dataTest:/var/lib/postgresql/data/pgdata"
    environment:
      PGDATA: /var/lib/postgresql/dataTest/pgdata
      POSTGRES_DB: sycast_test
      POSTGRES_USER: sycast_test
      POSTGRES_PASSWORD: sycast_test

  frontend:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
      args:
        UID: $UID
        GUID: $GUID
    ports:
      - $VUE_PORT:8080
    volumes:
      - "./shared/frontend:/var/www/frontend"
      - "./shared/site:/var/www/site"
    tty: true
    working_dir: "/var/www/frontend"